language: ruby
cache: bundler

rvm:
  - 1.9.3
  - 2.0.0

script: 'bundle exec rake'

services:
  - mongodb
before_script:
  - sleep 15  

notifications:
  email:
    recipients:
      - felix.abele@gmail.com
    on_failure: change
    on_success: never